<?php
session_start();
require('db.php');
require('fpdf.php');

$name = strtoupper($_SESSION['player_name']);
$player_id = $_SESSION['player_id'];
$amount = $_SESSION['balance'];
$date = date('d-m-Y');
$amount_words = strtoupper(numberToWords($amount)) . ' RUPEES ONLY';

// Cheque file save path
$cheque_dir = "cheques/";
if (!is_dir($cheque_dir)) {
    mkdir($cheque_dir, 0777, true);
}
$file_name = $cheque_dir . $player_id . '_' . str_replace(' ', '_', $_SESSION['player_name'])  . "_cheque.pdf";
//PDF SECTION START-------------------------------------------------------------
// PDF Generate
$pdf = new FPDF();
$pdf->AddPage();

//  cheque box with light blue background
$pdf->SetFillColor(230, 240, 255);
$pdf->Rect(10, 30, 190, 120, 'DF');

// Title
$pdf->SetFont('Arial', 'B', 16);
$pdf->SetTextColor(0, 0, 128);
$pdf->SetXY(10, 35);
$pdf->Cell(0, 10, 'KBC DUMMY BANK CHEQUE', 0, 1, 'C');
$pdf->SetTextColor(0, 0, 0);

// Bank + Date
$pdf->SetFont('Arial', 'B', 12);
$pdf->SetXY(15, 50);
$pdf->Cell(100, 8, "Bank: KBC NATIONAL BANK LTD.", 0, 0, 'L');
$pdf->Cell(0, 8, "Date: " . $date, 0, 1, 'R');

// Payee line
$pdf->SetFont('Arial', '', 12);
$pdf->SetXY(15, 65);
$pdf->Cell(45, 8, "Pay to the Order of:", 0, 0, 'L');
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, $name, 0, 1, 'L');
$pdf->Line(60, 73, 190, 73);

// Amount
$pdf->SetFont('Arial', 'B', 12);
$pdf->SetXY(15, 80);
$pdf->Cell(30, 8, "Amount:", 0, 0, 'L');
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, "INR " . number_format($amount) . " /-", 0, 1, 'L');
$pdf->Line(45, 88, 100, 88);

// Amount in words
$pdf->SetFont('Arial', '', 12);
$pdf->SetXY(15, 95);
$pdf->Cell(45, 8, "Amount in words:", 0, 0, 'L');
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, $amount_words, 0, 1, 'L');
$pdf->Line(60, 103, 190, 103);

// Signature (bottom-right)
$signature_image = 'images/signature.png';
if (file_exists($signature_image)) {
    $pdf->Image($signature_image, 135, 120, 40, 15); 
}
$pdf->Line(135, 138, 180, 138);
$pdf->SetXY(135, 139);
$pdf->SetFont('Arial', 'I', 10);
$pdf->Cell(45, 6, "Authorized Signatory", 0, 1, 'C');

// Footer note
$pdf->SetFont('Arial', 'I', 9);
$pdf->SetTextColor(100, 100, 100);
$pdf->SetXY(15, 150);
$pdf->Cell(0, 8, "This is a demo cheque generated by KBC Game Project.", 0, 1, 'L');
//PDF SECTION END------------------------------------------------------------------

// Save file on server
$pdf->Output('F', $file_name);

// SAVE IN DB
$method = 'cheque';
$stmt = $conn->prepare("INSERT INTO players (player_id, name, amount, method, cheque_file) 
                        VALUES (?, ?, ?, ?, ?) 
                        ON DUPLICATE KEY UPDATE cheque_file = VALUES(cheque_file), method = VALUES(method), amount = VALUES(amount)");
$stmt->bind_param("ssiss", $player_id, $name, $amount, $method, $file_name);
$stmt->execute();
$stmt->close();

header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="' . basename($file_name) . '"');
readfile($file_name);
exit();

// Number to words function
function numberToWords($number) {
    $ones = array(
        0=>"Zero",1=>"One",2=>"Two",3=>"Three",4=>"Four",5=>"Five",
        6=>"Six",7=>"Seven",8=>"Eight",9=>"Nine",10=>"Ten",
        11=>"Eleven",12=>"Twelve",13=>"Thirteen",14=>"Fourteen",
        15=>"Fifteen",16=>"Sixteen",17=>"Seventeen",18=>"Eighteen",19=>"Nineteen"
    );
    $tens = array(0=>"",1=>"Ten",2=>"Twenty",3=>"Thirty",4=>"Forty",
        5=>"Fifty",6=>"Sixty",7=>"Seventy",8=>"Eighty",9=>"Ninety");

    if ($number == 0) return "Zero";
    $words = "";

    if ($number >= 1000) {
        $words .= numberToWords(intval($number/1000)) . " Thousand ";
        $number = $number % 1000;
    }
    if ($number >= 100) {
        $words .= $ones[intval($number/100)] . " Hundred ";
        $number = $number % 100;
    }
    if ($number > 0) {
        if ($number < 20) $words .= $ones[$number];
        else {
            $words .= $tens[intval($number/10)];
            if ($number % 10 > 0) $words .= " " . $ones[$number%10];
        }
    }
    return trim($words);
}
?>
